/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe.filaOld;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import jframe.menuPrincipal.MiRenderer;
import jframe.menuPrincipal.date;

/**
 *
 * @author Gustavo
 */
public final class Alarmas_2021 extends javax.swing.JFrame {

    date date = new date();
    String user = System.getProperty("user.name");
    File fichero2 = new File("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\JFrame\\src\\file\\entrada.csv");
    File fichero = new File("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\JFrame\\src\\file\\Alarmas_05-10-2021_14-01-2022.csv");
    File fichero_temporal = new File("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\JFrame\\src\\file\\temporal.csv");
    File ficheroAlarmas = new File("C:\\Users\\" + user + "\\Desktop\\Fichero_Alarmas_05-10-2021_14-01-2022.csv");

    /**
     * Creates new form Alarmas
     */
    public Alarmas_2021() {
        MiRenderer m = new MiRenderer();
        initComponents();
        ficheroApp();
        this.setTitle("Control de alarmas");
        this.setLocationRelativeTo(Alarmas_2021.this);
        setIconImage(new ImageIcon(getClass().getResource("/img/IconoJFrame.png")).getImage());
        this.getContentPane().setBackground(new Color(243, 233, 147));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(true);
        NumPersonas();
        MostrarTabla();
        tablaAlarmas.getTableHeader().setFont(new Font("Courier New", 1, 18));
        tablaAlarmas.getTableHeader().setBackground(Color.blue);
        tablaAlarmas.getTableHeader().setForeground(Color.white);
        tablaAlarmas.getTableHeader().setPreferredSize(new java.awt.Dimension(50, 50));
        tablaAlarmas.setRowHeight(30);
        tablaAlarmas.setRowMargin(10);

        for (int i = 0; i < tablaAlarmas.getColumnCount(); i++) {
            tablaAlarmas.getColumnModel().getColumn(i).setCellRenderer(m);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAlarmas = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        NumPersonas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtHoraAviso = new javax.swing.JTextField();
        txtDescripZona = new javax.swing.JTextField();
        txtLazoModulo = new javax.swing.JTextField();
        txtAvisoA = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtHoraContestacion = new javax.swing.JTextField();
        txtDescripFalloAlarma = new javax.swing.JTextField();
        txtVigilante = new javax.swing.JTextField();
        txtNotas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMesAno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNumZona = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnActualizarMenu = new javax.swing.JMenuItem();
        btnBuscarMenu = new javax.swing.JMenuItem();
        btnLimpiarDatosMenu = new javax.swing.JMenuItem();
        btnFicheroMenu = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 233, 147));

        tablaAlarmas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaAlarmas.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        tablaAlarmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mes - Año", "Fecha", "Hora aviso", "Hora rearme", "Nº Zona", "Descrip. Zona", "Descrip. Fallo/Alarma", "Lazo y Módulo", "Aviso dado a", "Vigilante", "Notas", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaAlarmas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaAlarmas.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tablaAlarmas.getTableHeader().setReorderingAllowed(false);
        tablaAlarmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAlarmasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaAlarmas);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText("Personas dentro de Planta:");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NumPersonas.setEditable(false);
        NumPersonas.setBackground(new java.awt.Color(255, 255, 255));
        NumPersonas.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        NumPersonas.setForeground(new java.awt.Color(204, 0, 0));
        NumPersonas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumPersonas.setBorder(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alarmas");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));

        txtHoraAviso.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtHoraAviso.setBorder(null);

        txtDescripZona.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtDescripZona.setBorder(null);

        txtLazoModulo.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtLazoModulo.setBorder(null);

        txtAvisoA.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtAvisoA.setBorder(null);

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtId.setBorder(null);

        txtHoraContestacion.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtHoraContestacion.setBorder(null);

        txtDescripFalloAlarma.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtDescripFalloAlarma.setBorder(null);

        txtVigilante.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtVigilante.setBorder(null);

        txtNotas.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtNotas.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setText("Vigilante:");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setText("Nº Zona:");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setText("Hora aviso:");

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setText("Fecha:");

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel6.setText("Hora rearme:");

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel7.setText("Mes - Año:");

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel8.setText("Descrip. Zona:");

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel9.setText("Lazo - Módulo:");

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel10.setText("Aviso dado a:");

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel11.setText("Descrip. Fallo/Alarma:");

        txtMesAno.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtMesAno.setBorder(null);

        jLabel12.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel12.setText("Id:");

        txtNumZona.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtNumZona.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel13.setText("Notas:");

        txtFecha.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtFecha.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescripZona, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumZona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoraContestacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoraAviso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMesAno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAvisoA)
                    .addComponent(txtDescripFalloAlarma)
                    .addComponent(txtVigilante)
                    .addComponent(txtNotas)
                    .addComponent(txtId)
                    .addComponent(txtLazoModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLazoModulo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAvisoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescripFalloAlarma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtMesAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoraAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHoraContestacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVigilante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescripZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        txtMesAno.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(NumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 96, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(NumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBorder(null);
        jMenuBar1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        jMenu1.setBorder(null);
        jMenu1.setForeground(new java.awt.Color(0, 0, 255));
        jMenu1.setMnemonic('m');
        jMenu1.setText("Menú");
        jMenu1.setToolTipText("<html>Menú principal<br/>Tambien se puede usar Alt + m</html>");
        jMenu1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N

        btnActualizarMenu.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnActualizarMenu.setForeground(new java.awt.Color(0, 0, 255));
        btnActualizarMenu.setText("Actualizar");
        btnActualizarMenu.setBorder(null);
        btnActualizarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnActualizarMenu);

        btnBuscarMenu.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnBuscarMenu.setForeground(new java.awt.Color(0, 0, 255));
        btnBuscarMenu.setText("Buscar");
        btnBuscarMenu.setToolTipText("<html>______________________________________<br/><br/>Modelo de búsquedas<br/>______________________________________<br/>- Mes - Año<br/>- Fecha<br/>- Nº Zona<br/></html>");
        btnBuscarMenu.setBorder(null);
        btnBuscarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnBuscarMenu);

        btnLimpiarDatosMenu.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnLimpiarDatosMenu.setForeground(new java.awt.Color(0, 0, 255));
        btnLimpiarDatosMenu.setText("Limpiar");
        btnLimpiarDatosMenu.setBorder(null);
        btnLimpiarDatosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarDatosMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnLimpiarDatosMenu);

        btnFicheroMenu.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnFicheroMenu.setForeground(new java.awt.Color(0, 0, 255));
        btnFicheroMenu.setText("Crear Fichero");
        btnFicheroMenu.setBorder(null);
        btnFicheroMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicheroMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnFicheroMenu);

        btnSalir.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 0, 0));
        btnSalir.setMnemonic('s');
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("<html>Pulsar para salir<br/>Tambien se puede usar Alt + s<br/>y a continuación entrer</html>");
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(btnSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ficheroApp() {
        if (!fichero.exists()) {
            JOptionPane.showMessageDialog(null, "\nHay un error en los fichero\nhable con el administrador.");
            return;
        }
    }

    public void NumPersonas() {
        String line;
        int i = 0;
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(fichero2));
            while ((line = br.readLine()) != null) {
                String[] numPersonas = line.split(";");
                if (numPersonas[2].equals("DENTRO")) {
                    i++;
                    String numPersonasString = String.valueOf(i);
                    NumPersonas.setText(numPersonasString);
                } else {
                    String SinPersonasString = String.valueOf(i);
                    NumPersonas.setText(SinPersonasString);
                }
            }
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    public void ListaEntradaSalidaEmpresa() {
        String line;
        try {
            BufferedReader br = null;
            br = new BufferedReader(new FileReader(fichero));
            while ((line = br.readLine()) != null) {
                String[] cod_tar = line.split(";");
                DefaultTableModel model = (DefaultTableModel) tablaAlarmas.getModel();
                TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(model);
                tablaAlarmas.setRowSorter(elQueOrdena);
                Vector row = new Vector();
                row.add(cod_tar[0]);
                row.add(cod_tar[1]);
                row.add(cod_tar[2]);
                row.add(cod_tar[3]);
                row.add(cod_tar[4]);
                row.add(cod_tar[5]);
                row.add(cod_tar[6]);
                row.add(cod_tar[7]);
                row.add(cod_tar[8]);
                row.add(cod_tar[9]);
                row.add(cod_tar[10]);
                row.add(cod_tar[11]);
                model.addRow(row);
            }
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    public void LimpiarCasillas() {
        txtMesAno.setText(null);
        txtFecha.setText(null);
        txtHoraAviso.setText(null);
        txtHoraContestacion.setText(null);
        txtNumZona.setText(null);
        txtDescripZona.setText(null);
        txtDescripFalloAlarma.setText(null);
        txtLazoModulo.setText(null);
        txtAvisoA.setText(null);
        txtVigilante.setText(null);
        txtNotas.setText(null);
        txtId.setText(null);
    }

    public void Seleccionar() {
        if (tablaAlarmas.getSelectedRowCount() > 0) {
            txtMesAno.setText(tablaAlarmas.getValueAt(tablaAlarmas.getSelectedRow(), 0).toString());
            txtFecha.setText(tablaAlarmas.getValueAt(tablaAlarmas.getSelectedRow(), 1).toString());
            txtHoraAviso.setText(tablaAlarmas.getValueAt(tablaAlarmas.getSelectedRow(), 2).toString());
            txtHoraContestacion.setText(tablaAlarmas.getValueAt(tablaAlarmas.getSelectedRow(), 3).toString());
            txtNumZona.setText(tablaAlarmas.getValueAt(tablaAlarmas.getSelectedRow(), 4).toString());
            txtDescripZona.setText(tablaAlarmas.getValueAt(tablaAlarmas.getSelectedRow(), 5).toString());
            txtDescripFalloAlarma.setText(tablaAlarmas.getValueAt(tablaAlarmas.getSelectedRow(), 6).toString());
            txtLazoModulo.setText(tablaAlarmas.getValueAt(tablaAlarmas.getSelectedRow(), 7).toString());
            txtAvisoA.setText(tablaAlarmas.getValueAt(tablaAlarmas.getSelectedRow(), 8).toString());
            txtVigilante.setText(tablaAlarmas.getValueAt(tablaAlarmas.getSelectedRow(), 9).toString());
            txtNotas.setText(tablaAlarmas.getValueAt(tablaAlarmas.getSelectedRow(), 10).toString());
            txtId.setText(tablaAlarmas.getValueAt(tablaAlarmas.getSelectedRow(), 11).toString());
        }
    }

    public void MostrarTabla() {
        String line;
        BufferedReader br = null;
        DefaultTableModel model = (DefaultTableModel) tablaAlarmas.getModel();
        TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(model);
        model.setRowCount(0);
        model.setRowCount(0);
        try {
            br = new BufferedReader(new FileReader(fichero));
            while ((line = br.readLine()) != null) {
                String[] tabla = line.split(";");
                tablaAlarmas.setRowSorter(elQueOrdena);
                Vector row = new Vector();
                row.add(tabla[0]);
                row.add(tabla[1]);
                row.add(tabla[2]);
                row.add(tabla[3]);
                row.add(tabla[4]);
                row.add(tabla[5]);
                row.add(tabla[6]);
                row.add(tabla[7]);
                row.add(tabla[8]);
                row.add(tabla[9]);
                row.add(tabla[10]);
                row.add(tabla[11]);
                model.addRow(row);
            }
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    public void Buscar() {
        String line;
        try {
            BufferedReader br = null;
            br = new BufferedReader(new FileReader(fichero));
            while ((line = br.readLine()) != null) {
                String[] cod_tar = line.split(";");
                if ((txtMesAno.getText().equalsIgnoreCase(cod_tar[0]) || txtFecha.getText().equalsIgnoreCase(cod_tar[1]))
                        || txtNumZona.getText().equalsIgnoreCase(cod_tar[4])) {
                    DefaultTableModel model = (DefaultTableModel) tablaAlarmas.getModel();
                    TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<>(model);
                    tablaAlarmas.setRowSorter(elQueOrdena);
                    Vector row = new Vector();
                    row.add(cod_tar[0]);
                    row.add(cod_tar[1]);
                    row.add(cod_tar[2]);
                    row.add(cod_tar[3]);
                    row.add(cod_tar[4]);
                    row.add(cod_tar[5]);
                    row.add(cod_tar[6]);
                    row.add(cod_tar[7]);
                    row.add(cod_tar[8]);
                    row.add(cod_tar[9]);
                    row.add(cod_tar[10]);
                    row.add(cod_tar[11]);
                    model.addRow(row);
                }
            }
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    public void toExcel() {
        BufferedWriter bw = null;
        DefaultTableModel model = (DefaultTableModel) tablaAlarmas.getModel();
        try {
            bw = new BufferedWriter(new FileWriter(ficheroAlarmas));
            for (int i = 0; i < model.getColumnCount(); i++) {
                bw.write(model.getColumnName(i) + "\t");
            }
            bw.write("\n");
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    bw.write(model.getValueAt(i, j).toString() + "\t");
                }
                bw.write("\n");
            }
            bw.close();
            JOptionPane.showMessageDialog(null, "\nEl fichero se ha creado correctamente.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    private void btnActualizarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMenuActionPerformed
        DefaultTableModel model = (DefaultTableModel) this.tablaAlarmas.getModel();
        model.setRowCount(0);
        model.setRowCount(0);
        NumPersonas();
        LimpiarCasillas();
        MostrarTabla();        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarMenuActionPerformed

    private void btnBuscarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMenuActionPerformed
        DefaultTableModel model = (DefaultTableModel) this.tablaAlarmas.getModel();
        model.setRowCount(0);
        model.setRowCount(0);
        Buscar();
        LimpiarCasillas();
    }//GEN-LAST:event_btnBuscarMenuActionPerformed

    private void btnLimpiarDatosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarDatosMenuActionPerformed
        LimpiarCasillas();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarDatosMenuActionPerformed

    private void btnFicheroMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicheroMenuActionPerformed
        toExcel();             // TODO add your handling code here:
    }//GEN-LAST:event_btnFicheroMenuActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tablaAlarmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlarmasMouseClicked
        Seleccionar();
    }//GEN-LAST:event_tablaAlarmasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NumPersonas;
    private javax.swing.JMenuItem btnActualizarMenu;
    private javax.swing.JMenuItem btnBuscarMenu;
    private javax.swing.JMenuItem btnFicheroMenu;
    private javax.swing.JMenuItem btnLimpiarDatosMenu;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaAlarmas;
    private javax.swing.JTextField txtAvisoA;
    private javax.swing.JTextField txtDescripFalloAlarma;
    private javax.swing.JTextField txtDescripZona;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHoraAviso;
    private javax.swing.JTextField txtHoraContestacion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLazoModulo;
    private javax.swing.JTextField txtMesAno;
    private javax.swing.JTextField txtNotas;
    private javax.swing.JTextField txtNumZona;
    private javax.swing.JTextField txtVigilante;
    // End of variables declaration//GEN-END:variables
}
