package jframe.filaOld;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import jframe.menuPrincipal.MiRenderer;
import jframe.menuPrincipal.date;

/**
 *
 * @author Gustavo
 */
public final class ListaEntrada2020_2021 extends javax.swing.JFrame {

    date date = new date();
    String user = System.getProperty("user.name");
    File fichero2 = new File("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\JFrame\\src\\file\\entrada.csv");
    File fichero = new File("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\JFrame\\src\\file\\Horarios_26-12-2020_03-03-2021.csv");
    File fichero_temporal = new File("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\JFrame\\src\\file\\temporal.csv");
    File ficheroEntradaSalida = new File("C:\\Users\\" + user + "\\Desktop\\Fichero_Entrada_Salida_Horarios_26-12-2020_03-03-2021.csv");

    /**
     * Creates new form ListaEntradaSalida
     */
    public ListaEntrada2020_2021() {
        MiRenderer m = new MiRenderer();
        initComponents();
        ficheroApp();
        this.setTitle("Registros Control Usuarios");
        this.setLocationRelativeTo(ListaEntrada2020_2021.this);
        setIconImage(new ImageIcon(getClass().getResource("/img/IconoJFrame.png")).getImage());
        this.getContentPane().setBackground(new Color(243, 233, 147));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ListaEntradaSalidaEmpresa();
        NumPersonas();
        TablaListaEntradaSalida.getTableHeader().setFont(new Font("Courier New", 1, 18));
        TablaListaEntradaSalida.getTableHeader().setBackground(Color.blue);
        TablaListaEntradaSalida.getTableHeader().setForeground(Color.white);
        TablaListaEntradaSalida.getTableHeader().setPreferredSize(new java.awt.Dimension(50, 50));
        TablaListaEntradaSalida.setRowHeight(30);
        TablaListaEntradaSalida.setRowMargin(10);

        for (int i = 0; i < TablaListaEntradaSalida.getColumnCount(); i++) {
            TablaListaEntradaSalida.getColumnModel().getColumn(i).setCellRenderer(m);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaListaEntradaSalida = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NumPersonas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNumeroVisita = new javax.swing.JTextField();
        txtTrabajoRealizar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEntradaHora = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtSalidaHora = new javax.swing.JTextField();
        txtEmpresa = new javax.swing.JTextField();
        txtTotalHora = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtAutoriza = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMesAno = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        txtSituacion = new javax.swing.JTextField();
        txtMatriculaRemolque = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtCasco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGafas = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtRejilla = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtNotas = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoTarjeta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnActualizarMenu = new javax.swing.JMenuItem();
        btnBuscarMenu = new javax.swing.JMenuItem();
        btnLimpiarDatosMenu = new javax.swing.JMenuItem();
        btnFicheroMenu = new javax.swing.JMenuItem();
        btnSalirMenu = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu5.setText("jMenu5");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 233, 147));

        TablaListaEntradaSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TablaListaEntradaSalida.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        TablaListaEntradaSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mes-Año", "Fecha", "Situacion", "Empresa", "Nombre", "Apellido", "Dni", "Codigo Tarjeta", "Numero Visita", "Trabajo a  Realizar", "Entrada", "Salida", "Total", "Autoriza", "Matricula", "Matricula Remolque", "Casco", "Gafas", "Rejilla", "Notas", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaListaEntradaSalida.setSelectionBackground(new java.awt.Color(153, 204, 255));
        TablaListaEntradaSalida.getTableHeader().setReorderingAllowed(false);
        TablaListaEntradaSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaListaEntradaSalidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaListaEntradaSalida);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registros");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Personas dentro de Planta:");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NumPersonas.setEditable(false);
        NumPersonas.setBackground(new java.awt.Color(255, 255, 255));
        NumPersonas.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        NumPersonas.setForeground(new java.awt.Color(204, 0, 0));
        NumPersonas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumPersonas.setBorder(null);

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel6.setText("Nombre:");

        txtNumeroVisita.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtNumeroVisita.setBorder(null);

        txtTrabajoRealizar.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTrabajoRealizar.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel7.setText("Apellido:");

        txtEntradaHora.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtEntradaHora.setBorder(null);

        txtFecha.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtFecha.setBorder(null);

        txtSalidaHora.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtSalidaHora.setBorder(null);

        txtEmpresa.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtEmpresa.setBorder(null);

        txtTotalHora.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTotalHora.setBorder(null);

        txtNombre.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtNombre.setBorder(null);

        txtAutoriza.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtAutoriza.setBorder(null);

        txtApellido.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtApellido.setBorder(null);

        jLabel12.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel12.setText("Matrícula:");

        txtMesAno.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtMesAno.setBorder(null);

        txtMatricula.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtMatricula.setBorder(null);

        txtSituacion.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtSituacion.setBorder(null);

        txtMatriculaRemolque.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtMatriculaRemolque.setBorder(null);

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel10.setText("Situación:");

        jLabel31.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel31.setText("Matricula Remolque:");

        jLabel32.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel32.setText("Casco:");

        txtCasco.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtCasco.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setText("DNI - NIF: ");

        txtGafas.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtGafas.setBorder(null);

        jLabel29.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel29.setText("Total:");

        jLabel33.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel33.setText("Gafas:");

        txtDni.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtDni.setBorder(null);

        jLabel34.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel34.setText("Rejilla:");

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel11.setText("Código Tarjeta:");

        txtRejilla.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtRejilla.setBorder(null);

        jLabel25.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel25.setText("Número Visita:");

        txtNotas.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtNotas.setBorder(null);

        jLabel30.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel30.setText("Autoriza:");

        jLabel35.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel35.setText("Notas:");

        jLabel26.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel26.setText("Trabajo:");

        jLabel36.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel36.setText("Id:");

        jLabel27.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel27.setText("Entrada:");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtId.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setText("Mes-Año (mm/yy):");

        jLabel28.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel28.setText("Salida:");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setText("Fecha (dd/mm/yy):");

        txtCodigoTarjeta.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtCodigoTarjeta.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setText("Empresa:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMesAno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSituacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtEntradaHora)
                    .addComponent(txtNumeroVisita, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTrabajoRealizar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigoTarjeta, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDni, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalHora, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSalidaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNotas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRejilla, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMatriculaRemolque, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCasco, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGafas)
                    .addComponent(txtAutoriza, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMesAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodigoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(txtNumeroVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTrabajoRealizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(txtEntradaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel6)
                            .addComponent(txtSalidaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtTotalHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAutoriza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txtMatriculaRemolque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCasco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txtGafas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRejilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(NumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(NumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBorder(null);
        jMenuBar1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        jMenu1.setBorder(null);
        jMenu1.setForeground(new java.awt.Color(0, 0, 255));
        jMenu1.setMnemonic('m');
        jMenu1.setText("Menú");
        jMenu1.setToolTipText("<html>Menú principal<br/>Tambien se puede usar Alt + m</html>");
        jMenu1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N

        btnActualizarMenu.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnActualizarMenu.setForeground(new java.awt.Color(0, 0, 255));
        btnActualizarMenu.setText("Actualizar");
        btnActualizarMenu.setBorder(null);
        btnActualizarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnActualizarMenu);

        btnBuscarMenu.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnBuscarMenu.setForeground(new java.awt.Color(0, 0, 255));
        btnBuscarMenu.setText("Buscar");
        btnBuscarMenu.setToolTipText("<html>______________________________________<br/><br/>Modelo de búsquedas<br/>______________________________________<br/>- Situación (Dentro o Fuera)<br/>- Mes-Año (mm/yy) - Empresa<br/>- Mes-Año (mm/yy)  - Nombre - Apellido<br/>- Fecha (dd/mm/yy) - Empresa<br/>- Fecha (dd/mm/yy) - Nombre - Apellido<br/></html>");
        btnBuscarMenu.setBorder(null);
        btnBuscarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnBuscarMenu);

        btnLimpiarDatosMenu.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnLimpiarDatosMenu.setForeground(new java.awt.Color(0, 0, 255));
        btnLimpiarDatosMenu.setText("Limpiar");
        btnLimpiarDatosMenu.setBorder(null);
        btnLimpiarDatosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarDatosMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnLimpiarDatosMenu);

        btnFicheroMenu.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnFicheroMenu.setForeground(new java.awt.Color(0, 0, 255));
        btnFicheroMenu.setText("Crear Fichero");
        btnFicheroMenu.setBorder(null);
        btnFicheroMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicheroMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnFicheroMenu);

        btnSalirMenu.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnSalirMenu.setForeground(new java.awt.Color(255, 0, 0));
        btnSalirMenu.setMnemonic('s');
        btnSalirMenu.setText("Salir");
        btnSalirMenu.setToolTipText("<html>Pulsar para salir<br/>Tambien se puede usar Alt + s<br/>y a continuación entrer</html>");
        btnSalirMenu.setBorder(null);
        btnSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnSalirMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ficheroApp() {
        if (!fichero.exists()) {
            JOptionPane.showMessageDialog(null, "\nHay un error en los fichero\nhable con el administrador.");
            return;
        }
    }

    public void NumPersonas() {
        String line;
        int i = 0;
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(fichero2));
            while ((line = br.readLine()) != null) {
                String[] numPersonas = line.split(";");
                if (numPersonas[2].equals("DENTRO")) {
                    i++;
                    String numPersonasString = String.valueOf(i);
                    NumPersonas.setText(numPersonasString);
                } else {
                    String SinPersonasString = String.valueOf(i);
                    NumPersonas.setText(SinPersonasString);
                }
            }
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    public void Seleccionar() {
        if (TablaListaEntradaSalida.getSelectedRowCount() > 0) {
            txtMesAno.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 0).toString());
            txtFecha.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 1).toString());
            txtSituacion.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 2).toString());
            txtEmpresa.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 3).toString());
            txtNombre.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 4).toString());
            txtApellido.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 5).toString());
            txtDni.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 6).toString());
            txtCodigoTarjeta.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 7).toString());
            txtNumeroVisita.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 8).toString());
            txtTrabajoRealizar.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 9).toString());
            txtEntradaHora.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 10).toString());
            txtSalidaHora.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 11).toString());
            txtTotalHora.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 12).toString());
            txtAutoriza.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 13).toString());
            txtMatricula.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 14).toString());
            txtMatriculaRemolque.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 15).toString());
            txtCasco.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 16).toString());
            txtGafas.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 17).toString());
            txtRejilla.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 18).toString());
            txtNotas.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 19).toString());
            txtId.setText(TablaListaEntradaSalida.getValueAt(TablaListaEntradaSalida.getSelectedRow(), 20).toString());
        }
    }

    public void LimpiarCasillas() {
        txtSituacion.setText(null);
        txtNombre.setText(null);
        txtMesAno.setText(null);
        txtFecha.setText(null);
        txtEmpresa.setText(null);
        txtApellido.setText(null);
        txtDni.setText(null);
        txtCodigoTarjeta.setText(null);
        txtNumeroVisita.setText(null);
        txtTrabajoRealizar.setText(null);
        txtEntradaHora.setText(null);
        txtSalidaHora.setText(null);
        txtTotalHora.setText(null);
        txtAutoriza.setText(null);
        txtMatricula.setText(null);
        txtMatriculaRemolque.setText(null);
        txtCasco.setText(null);
        txtGafas.setText(null);
        txtRejilla.setText(null);
        txtNotas.setText(null);
        txtId.setText(null);
    }

    public void Buscar() {
        String line;
        try {
            BufferedReader br = null;
            br = new BufferedReader(new FileReader(fichero));
            while ((line = br.readLine()) != null) {
                String[] cod_tar = line.split(";");
                if ((txtFecha.getText().equalsIgnoreCase(cod_tar[1]) && txtNombre.getText().equalsIgnoreCase(cod_tar[4])
                        && txtApellido.getText().equalsIgnoreCase(cod_tar[5]))
                        || (txtSituacion.getText().equalsIgnoreCase(cod_tar[2]))
                        || (txtFecha.getText().equalsIgnoreCase(cod_tar[1]) && txtEmpresa.getText().equalsIgnoreCase(cod_tar[3]))
                        || (txtMesAno.getText().equalsIgnoreCase(cod_tar[0]) && txtNombre.getText().equalsIgnoreCase(cod_tar[4])
                        && txtApellido.getText().equalsIgnoreCase(cod_tar[5]))
                        || (txtMesAno.getText().equalsIgnoreCase(cod_tar[0]) && txtEmpresa.getText().equalsIgnoreCase(cod_tar[3]))) {
                    DefaultTableModel model = (DefaultTableModel) TablaListaEntradaSalida.getModel();
                    TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<>(model);
                    TablaListaEntradaSalida.setRowSorter(elQueOrdena);
                    Vector row = new Vector();
                    row.add(cod_tar[0]);
                    row.add(cod_tar[1]);
                    row.add(cod_tar[2]);
                    row.add(cod_tar[3]);
                    row.add(cod_tar[4]);
                    row.add(cod_tar[5]);
                    row.add(cod_tar[6]);
                    row.add(cod_tar[7]);
                    row.add(cod_tar[8]);
                    row.add(cod_tar[9]);
                    row.add(cod_tar[10]);
                    row.add(cod_tar[11]);
                    row.add(cod_tar[12]);
                    row.add(cod_tar[13]);
                    row.add(cod_tar[14]);
                    row.add(cod_tar[15]);
                    row.add(cod_tar[16]);
                    row.add(cod_tar[17]);
                    row.add(cod_tar[18]);
                    row.add(cod_tar[19]);
                    row.add(cod_tar[20]);
                    model.addRow(row);
                }
            }
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    public void ListaEntradaSalidaEmpresa() {
        String line;
        try {
            BufferedReader br = null;
            br = new BufferedReader(new FileReader(fichero));
            while ((line = br.readLine()) != null) {
                String[] cod_tar = line.split(";");
                DefaultTableModel model = (DefaultTableModel) TablaListaEntradaSalida.getModel();
                TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(model);
                TablaListaEntradaSalida.setRowSorter(elQueOrdena);
                Vector row = new Vector();
                row.add(cod_tar[0]);
                row.add(cod_tar[1]);
                row.add(cod_tar[2]);
                row.add(cod_tar[3]);
                row.add(cod_tar[4]);
                row.add(cod_tar[5]);
                row.add(cod_tar[6]);
                row.add(cod_tar[7]);
                row.add(cod_tar[8]);
                row.add(cod_tar[9]);
                row.add(cod_tar[10]);
                row.add(cod_tar[11]);
                row.add(cod_tar[12]);
                row.add(cod_tar[13]);
                row.add(cod_tar[14]);
                row.add(cod_tar[15]);
                row.add(cod_tar[16]);
                row.add(cod_tar[17]);
                row.add(cod_tar[18]);
                row.add(cod_tar[19]);
                row.add(cod_tar[20]);
                model.addRow(row);
            }
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    public void toExcel() {
        BufferedWriter bw = null;
        DefaultTableModel model = (DefaultTableModel) TablaListaEntradaSalida.getModel();
        try {
            bw = new BufferedWriter(new FileWriter(ficheroEntradaSalida));
            for (int i = 0; i < model.getColumnCount(); i++) {
                bw.write(model.getColumnName(i) + "\t");
            }
            bw.write("\n");
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    bw.write(model.getValueAt(i, j).toString() + "\t");
                }
                bw.write("\n");
            }
            bw.close();
            JOptionPane.showMessageDialog(null, "\nEl fichero se ha creado correctamente.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    private void btnSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMenuActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirMenuActionPerformed

    private void btnFicheroMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicheroMenuActionPerformed
        toExcel();
    }//GEN-LAST:event_btnFicheroMenuActionPerformed

    private void btnLimpiarDatosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarDatosMenuActionPerformed
        LimpiarCasillas();
    }//GEN-LAST:event_btnLimpiarDatosMenuActionPerformed

    private void btnActualizarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMenuActionPerformed
        DefaultTableModel model = (DefaultTableModel) this.TablaListaEntradaSalida.getModel();
        model.setRowCount(0);
        model.setRowCount(0);
        ListaEntradaSalidaEmpresa();
        NumPersonas();
    }//GEN-LAST:event_btnActualizarMenuActionPerformed

    private void btnBuscarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMenuActionPerformed
        DefaultTableModel model = (DefaultTableModel) this.TablaListaEntradaSalida.getModel();
        model.setRowCount(0);
        model.setRowCount(0);
        Buscar();
        LimpiarCasillas();
    }//GEN-LAST:event_btnBuscarMenuActionPerformed

    private void TablaListaEntradaSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaListaEntradaSalidaMouseClicked
        Seleccionar();
    }//GEN-LAST:event_TablaListaEntradaSalidaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NumPersonas;
    private javax.swing.JTable TablaListaEntradaSalida;
    private javax.swing.JMenuItem btnActualizarMenu;
    private javax.swing.JMenuItem btnBuscarMenu;
    private javax.swing.JMenuItem btnFicheroMenu;
    private javax.swing.JMenuItem btnLimpiarDatosMenu;
    private javax.swing.JMenuItem btnSalirMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtAutoriza;
    private javax.swing.JTextField txtCasco;
    private javax.swing.JTextField txtCodigoTarjeta;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtEntradaHora;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtGafas;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMatriculaRemolque;
    private javax.swing.JTextField txtMesAno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNotas;
    private javax.swing.JTextField txtNumeroVisita;
    private javax.swing.JTextField txtRejilla;
    private javax.swing.JTextField txtSalidaHora;
    private javax.swing.JTextField txtSituacion;
    private javax.swing.JTextField txtTotalHora;
    private javax.swing.JTextField txtTrabajoRealizar;
    // End of variables declaration//GEN-END:variables
}
