package jframe;

import jframe.menuPrincipal.MiRenderer;
import jframe.menuPrincipal.date;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Gustavo_Senorans
 */
public class ListaMaterial extends javax.swing.JFrame {

    date date = new date();
    String user = System.getProperty("user.name");
    File fichero2 = new File("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\JFrame\\src\\file\\entrada.csv");
    File fichero = new File("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\JFrame\\src\\file\\listado_mercancia.csv");
    File fichero_temporal = new File("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\JFrame\\src\\file\\temporal.csv");
    File ficheroistaMaterial = new File("C:\\Users\\" + user + "\\Desktop\\Fichero_Lista_Material.csv");

    /**
     * Creates new form ListaMaterial
     */
    public ListaMaterial() {
        MiRenderer m = new MiRenderer();
        initComponents();
        ficheroApp();
        this.setTitle("Inicio Control Usuarios");
        this.setLocationRelativeTo(ListaMaterial.this);
        setIconImage(new ImageIcon(getClass().getResource("/img/IconoJFrame.png")).getImage());
        this.getContentPane().setBackground(new Color(243, 233, 147));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(true);
        modificarFileEntrada();
        MostrarTabla();
        NumPersonas();
        datos();
        tablaListaMaterial.getTableHeader().setFont(new Font("Courier New", 1, 18));
        tablaListaMaterial.getTableHeader().setBackground(Color.blue);
        tablaListaMaterial.getTableHeader().setForeground(Color.white);
        tablaListaMaterial.getTableHeader().setPreferredSize(new java.awt.Dimension(50, 50));
        tablaListaMaterial.setRowHeight(30);
        tablaListaMaterial.setRowMargin(10);

        for (int i = 0; i < tablaListaMaterial.getColumnCount(); i++) {
            tablaListaMaterial.getColumnModel().getColumn(i).setCellRenderer(m);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListaMaterial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NumPersonas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtProveedor = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtDepartamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreComercial = new javax.swing.JTextField();
        txtAlmacenaje = new javax.swing.JTextField();
        txtPresentacion = new javax.swing.JTextField();
        btnGuardarModificacion1 = new javax.swing.JButton();
        btnModificarId1 = new javax.swing.JButton();
        btnBuscar1 = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnActualizar = new javax.swing.JMenuItem();
        btnEliminar = new javax.swing.JMenuItem();
        btnLimpiarDatos = new javax.swing.JMenuItem();
        btnCrearFichero = new javax.swing.JMenuItem();
        btnSalirMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 233, 147));

        tablaListaMaterial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaListaMaterial.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        tablaListaMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Proveedor", "Presentación", "Almacenaje", "Nombre comercial", "Departamento", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaListaMaterial.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tablaListaMaterial.getTableHeader().setReorderingAllowed(false);
        tablaListaMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListaMaterialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaListaMaterial);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista Materiales");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Personas dentro de Planta:");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NumPersonas.setEditable(false);
        NumPersonas.setBackground(new java.awt.Color(255, 255, 255));
        NumPersonas.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        NumPersonas.setForeground(new java.awt.Color(204, 0, 0));
        NumPersonas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumPersonas.setBorder(null);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jLabel13.setAutoscrolls(true);
        jLabel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));

        txtProveedor.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtProveedor.setBorder(null);

        txtProducto.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtProducto.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel8.setText("Departamento:");

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel7.setText("Nombre comercial:");

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel6.setText("Id:");

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setText("Almacenaje:");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setText("Presentación:");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtId.setBorder(null);

        txtDepartamento.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtDepartamento.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setText("Proveedor:");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setText("Producto:");

        txtNombreComercial.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtNombreComercial.setBorder(null);

        txtAlmacenaje.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtAlmacenaje.setBorder(null);

        txtPresentacion.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtPresentacion.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtAlmacenaje, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtAlmacenaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardarModificacion1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnGuardarModificacion1.setForeground(new java.awt.Color(0, 0, 255));
        btnGuardarModificacion1.setMnemonic('r');
        btnGuardarModificacion1.setText("Guardar Modificación");
        btnGuardarModificacion1.setToolTipText("<html>Guardar modificación.<br/>Tambien puede usar Alt + r</html>");
        btnGuardarModificacion1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarModificacion1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarModificacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarModificacion1ActionPerformed(evt);
            }
        });

        btnModificarId1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnModificarId1.setForeground(new java.awt.Color(0, 0, 255));
        btnModificarId1.setMnemonic('i');
        btnModificarId1.setText("ID");
        btnModificarId1.setToolTipText("<html>Modificar ID.<br/>Tambien puede usar Alt + i</html>");
        btnModificarId1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificarId1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarId1ActionPerformed(evt);
            }
        });

        btnBuscar1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnBuscar1.setForeground(new java.awt.Color(0, 0, 255));
        btnBuscar1.setMnemonic('b');
        btnBuscar1.setText("Buscar");
        btnBuscar1.setToolTipText("<html>______________________________________<br/><br/>Modelo de búsquedas<br/>______________________________________<br/>- Producto<br/>- Proveedor<br/>Tambien puede usar Alt + b<br/></html>");
        btnBuscar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        btnGuardar1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(0, 0, 255));
        btnGuardar1.setMnemonic('g');
        btnGuardar1.setText("Guardar");
        btnGuardar1.setToolTipText("<html>Guardar entrada.<br/>Tambien puede usar Alt + g</html>");
        btnGuardar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(NumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificarId1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardarModificacion1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(NumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar1)
                    .addComponent(btnBuscar1)
                    .addComponent(btnModificarId1)
                    .addComponent(btnGuardarModificacion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBorder(null);
        jMenuBar1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        jMenu1.setBorder(null);
        jMenu1.setForeground(new java.awt.Color(0, 0, 255));
        jMenu1.setMnemonic('m');
        jMenu1.setText("Menú");
        jMenu1.setToolTipText("<html>Menú principal<br/>lista material.<br/>Tambien se puede usar Alt + m</html>");
        jMenu1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jMenu1.setHideActionText(true);

        btnActualizar.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jMenu1.add(btnActualizar);

        btnEliminar.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jMenu1.add(btnEliminar);

        btnLimpiarDatos.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnLimpiarDatos.setForeground(new java.awt.Color(0, 0, 255));
        btnLimpiarDatos.setText("Limpiar");
        btnLimpiarDatos.setBorder(null);
        btnLimpiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarDatosActionPerformed(evt);
            }
        });
        jMenu1.add(btnLimpiarDatos);

        btnCrearFichero.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnCrearFichero.setForeground(new java.awt.Color(0, 0, 255));
        btnCrearFichero.setText("Crear Fichero");
        btnCrearFichero.setBorder(null);
        btnCrearFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearFicheroActionPerformed(evt);
            }
        });
        jMenu1.add(btnCrearFichero);

        btnSalirMenu.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnSalirMenu.setForeground(new java.awt.Color(255, 0, 0));
        btnSalirMenu.setMnemonic('s');
        btnSalirMenu.setText("Salir");
        btnSalirMenu.setToolTipText("<html>Pulsar para salir<br/>Tambien se puede usar Alt + s<br/>y a continuación entrer</html>");
        btnSalirMenu.setBorder(null);
        btnSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnSalirMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ficheroApp() {
        if (!fichero.exists()) {
            JOptionPane.showMessageDialog(null, "\nHay un error en los fichero\nhable con el administrador.");
        }
    }

    public void NumPersonas() {
        String line;
        int i = 0;
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(fichero2));
            while ((line = br.readLine()) != null) {
                String[] numPersonas = line.split(";");
                if (numPersonas[2].equals("DENTRO")) {
                    i++;
                    String numPersonasString = String.valueOf(i);
                    NumPersonas.setText(numPersonasString);
                } else {
                    String SinPersonasString = String.valueOf(i);
                    NumPersonas.setText(SinPersonasString);
                }
            }
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    public void datos() {
        String line2;
        int i = 0;
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(fichero));
            while ((line2 = br.readLine()) != null) {
                i++;
                String id = String.valueOf(i);
                txtId.setText(id);
            }
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    public void MostrarTabla() {
        String line;
        BufferedReader br = null;
        DefaultTableModel model = (DefaultTableModel) tablaListaMaterial.getModel();
        TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(model);
        model.setRowCount(0);
        model.setRowCount(0);
        try {
            br = new BufferedReader(new FileReader(fichero));
            while ((line = br.readLine()) != null) {
                String[] tabla = line.split(";");
                tablaListaMaterial.setRowSorter(elQueOrdena);
                Vector row = new Vector();
                row.add(tabla[0]);
                row.add(tabla[1]);
                row.add(tabla[2]);
                row.add(tabla[3]);
                row.add(tabla[4]);
                row.add(tabla[5]);
                row.add(tabla[6]);
                model.addRow(row);
            }
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    public void Seleccionar() {
        if (tablaListaMaterial.getSelectedRowCount() > 0) {
            txtProducto.setText(tablaListaMaterial.getValueAt(tablaListaMaterial.getSelectedRow(), 0).toString());
            txtProveedor.setText(tablaListaMaterial.getValueAt(tablaListaMaterial.getSelectedRow(), 1).toString());
            txtPresentacion.setText(tablaListaMaterial.getValueAt(tablaListaMaterial.getSelectedRow(), 2).toString());
            txtAlmacenaje.setText(tablaListaMaterial.getValueAt(tablaListaMaterial.getSelectedRow(), 3).toString());
            txtNombreComercial.setText(tablaListaMaterial.getValueAt(tablaListaMaterial.getSelectedRow(), 4).toString());
            txtDepartamento.setText(tablaListaMaterial.getValueAt(tablaListaMaterial.getSelectedRow(), 5).toString());
            txtId.setText(tablaListaMaterial.getValueAt(tablaListaMaterial.getSelectedRow(), 6).toString());
        }
    }

    public void LimpiarCasillas() {
        txtProducto.setText(null);
        txtProveedor.setText(null);
        txtPresentacion.setText(null);
        txtAlmacenaje.setText(null);
        txtNombreComercial.setText(null);
        txtDepartamento.setText(null);
        txtId.setText(null);
    }

    public void GuardarListaMaterial() {
        BufferedReader br = null;
        String line;
        int d = 0;
        try {
            BufferedWriter bw = null;
            br = new BufferedReader(new FileReader(fichero));
            bw = new BufferedWriter(new FileWriter(fichero, true));
            if ((line = br.readLine()) != null) {
                String[] busqueda = line.split(";");
                d++;

                String producto = txtProducto.getText();
                busqueda[0] = producto;

                String proveedor = txtProveedor.getText();
                busqueda[1] = proveedor;

                String presentacion = txtPresentacion.getText();
                busqueda[2] = presentacion;

                String almacenaje = txtAlmacenaje.getText();
                busqueda[3] = almacenaje;

                String nombreComercial = txtNombreComercial.getText();
                busqueda[4] = nombreComercial;

                String departamento = txtDepartamento.getText();
                busqueda[5] = departamento;

                String id2 = txtId.getText();
                busqueda[6] = id2;

                bw.write(busqueda[0] + ';' + busqueda[1] + ';' + busqueda[2] + ';' + busqueda[3] + ';' + busqueda[4] + ';'
                        + busqueda[5] + ';' + busqueda[6] + "\n");
            }
            bw.flush();
            br.close();
            bw.close();
            if (d == 0) {
                JOptionPane.showMessageDialog(null, "\nNO SE PUEDEN GUARDAR LOS DATOS.");
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, date.fecha() + "\nError: " + e);
        }
    }

    public void GuardarNuevoId() {
        try {
            String line;
            BufferedReader br = null;
            br = new BufferedReader(new FileReader(fichero));
            while ((line = br.readLine()) != null) {
                String[] busqueda = line.split(";");
                if (txtId.getText().equals("") || txtId.getText().equals(busqueda[6])) {
                    JOptionPane.showMessageDialog(null, "\nEl Id está bacio o se repite el id.");
                    br.close();
                    return;
                } else if (txtProducto.getText().equals("")
                        || txtProveedor.getText().equals("")
                        || txtPresentacion.getText().equals("")
                        || txtAlmacenaje.getText().equals("")
                        || txtNombreComercial.getText().equals("")
                        || txtDepartamento.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "\nFaltan campos por rellenar.");
                    br.close();
                    return;
                }
            }
            br.close();
            GuardarListaMaterial();
            LimpiarCasillas();
            MostrarTabla();
            datos();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, date.fecha() + "\nError: " + e);
        }
    }

    public void GuardarModificaciones() {
        int i = 0;
        try {
            String line;
            String producto = txtProducto.getText();
            String proveedor = txtProveedor.getText();
            String presentacion = txtPresentacion.getText();
            String almacenaje = txtAlmacenaje.getText();
            String nombreComercial = txtNombreComercial.getText();
            String departamento = txtDepartamento.getText();
            String id = txtId.getText();
            BufferedReader br = null;
            BufferedWriter bw = null;
            br = new BufferedReader(new FileReader(fichero));
            bw = new BufferedWriter(new FileWriter(fichero_temporal));
            while ((line = br.readLine()) != null) {
                String[] busqueda = line.split(";");
                if (busqueda[6].equals(id)) {
                    i++;
                    busqueda[0] = (busqueda[0].replace(busqueda[0], producto));
                    busqueda[1] = (busqueda[1].replace(busqueda[1], proveedor));
                    busqueda[2] = (busqueda[2].replace(busqueda[2], presentacion));
                    busqueda[3] = (busqueda[3].replace(busqueda[3], almacenaje));
                    busqueda[4] = (busqueda[4].replace(busqueda[4], nombreComercial));
                    busqueda[5] = (busqueda[5].replace(busqueda[5], departamento));
                    busqueda[6] = (busqueda[6].replace(busqueda[6], id));
                }
                bw.write(busqueda[0] + ';' + busqueda[1] + ';' + busqueda[2] + ';' + busqueda[3] + ';' + busqueda[4] + ';'
                        + busqueda[5] + ';' + busqueda[6] + "\n");
            }
            bw.flush();
            br.close();
            bw.close();
            if (i == 0) {
                JOptionPane.showMessageDialog(null, "\nNO SE ENCONTRARON DATOS RELACIONADOS A LA BÚSQUEDA");
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, date.fecha() + "\nError: " + e);
        }
        fichero.delete();
        fichero_temporal.renameTo(fichero);
    }

    public void toExcel() {
        BufferedWriter bw = null;
        DefaultTableModel model = (DefaultTableModel) tablaListaMaterial.getModel();
        try {
            bw = new BufferedWriter(new FileWriter(ficheroistaMaterial));
            for (int i = 0; i < model.getColumnCount(); i++) {
                bw.write(model.getColumnName(i) + "\t");
            }
            bw.write("\n");
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    bw.write(model.getValueAt(i, j).toString() + "\t");
                }
                bw.write("\n");
            }
            bw.close();
            JOptionPane.showMessageDialog(null, "\nEl fichero se ha creado correctamente.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    public void Buscar() {
        String line;
        try {
            BufferedReader br = null;
            br = new BufferedReader(new FileReader(fichero));
            while ((line = br.readLine()) != null) {
                String[] cod_tar = line.split(";");
                if (txtProducto.getText().equalsIgnoreCase(cod_tar[0]) || txtProveedor.getText().equalsIgnoreCase(cod_tar[1])) {
                    DefaultTableModel model = (DefaultTableModel) tablaListaMaterial.getModel();
                    TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<>(model);
                    tablaListaMaterial.setRowSorter(elQueOrdena);
                    Vector row = new Vector();
                    row.add(cod_tar[0]);
                    row.add(cod_tar[1]);
                    row.add(cod_tar[2]);
                    row.add(cod_tar[3]);
                    row.add(cod_tar[4]);
                    row.add(cod_tar[5]);
                    row.add(cod_tar[6]);
                    model.addRow(row);
                }
            }
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    public void eliminarFila() {
        String line;
        BufferedReader br = null;
        BufferedWriter bw = null;
        ArrayList<String> al = new ArrayList<>();
        try {
            br = new BufferedReader(new FileReader(fichero));
            bw = new BufferedWriter(new FileWriter(fichero_temporal));
            while ((line = br.readLine()) != null) {
                String[] tabla = line.split(";");
                al.add(tabla[0] + ';' + tabla[1] + ';' + tabla[2]
                        + ';' + tabla[3] + ';' + tabla[4] + ';'
                        + tabla[5] + ';' + tabla[6] + "\n");
            }
            int i = Integer.parseInt(txtId.getText());
            int confirmado = JOptionPane.showOptionDialog(null,
                    "¿Esta seguro de eliminar los datos?",
                    "Eliminar datos",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null, new Object[]{"Si", "No"}, "No");
            switch (confirmado) {
                case JOptionPane.OK_OPTION:
                    al.remove(i);
                    JOptionPane.showMessageDialog(null, "Datos eliminados correctamente");
                    br.close();
                    break;
                case JOptionPane.NO_OPTION:
                    JOptionPane.showMessageDialog(null, "No se borrarán los datos");
                    br.close();
                    break;
                default:
                    br.close();
                    break;
            }
            for (String prueba : al) {
                bw.write(prueba);
            }
            bw.flush();
            br.close();
            bw.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
        fichero.delete();
        fichero_temporal.renameTo(fichero);
    }

    public String modificarFileEntrada() {
        BufferedReader br = null;
        BufferedWriter bw = null;
        String line;
        int i = 0;
        try {
            br = new BufferedReader(new FileReader(fichero));
            bw = new BufferedWriter(new FileWriter(fichero_temporal));
            while ((line = br.readLine()) != null) {
                String[] tabla = line.split(";");
                tabla[0] = (tabla[0].replace(tabla[0], tabla[0]));
                tabla[1] = (tabla[1].replace(tabla[1], tabla[1]));
                tabla[2] = (tabla[2].replace(tabla[2], tabla[2]));
                tabla[3] = (tabla[3].replace(tabla[3], tabla[3]));
                tabla[4] = (tabla[4].replace(tabla[4], tabla[4]));
                tabla[5] = (tabla[5].replace(tabla[5], tabla[5]));
                bw.write(tabla[0] + ';' + tabla[1] + ';' + tabla[2]
                        + ';' + tabla[3] + ';' + tabla[4] + ';' + tabla[5] + ';' + i + "\n");
                i++;
            }
            bw.flush();
            bw.close();
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
        fichero.delete();
        fichero_temporal.renameTo(fichero);
        return " ";
    }

    public void EntradaMultiple() {
        String line2;
        int i = 0;
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(fichero));
            while ((line2 = br.readLine()) != null) {
                i++;
                String id = String.valueOf(i);
                txtId.setText(id);
            }
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
        txtProveedor.setText(txtProveedor.getText());
        txtProveedor.setText(txtNombreComercial.getText());

        txtProducto.setText(null);
        txtPresentacion.setText(null);
        txtAlmacenaje.setText(null);
        txtNombreComercial.setText(null);
    }

    private void btnSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMenuActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirMenuActionPerformed

    private void btnCrearFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearFicheroActionPerformed
        toExcel();
    }//GEN-LAST:event_btnCrearFicheroActionPerformed

    private void btnLimpiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarDatosActionPerformed
        LimpiarCasillas();
    }//GEN-LAST:event_btnLimpiarDatosActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        DefaultTableModel model = (DefaultTableModel) this.tablaListaMaterial.getModel();
        model.setRowCount(0);
        model.setRowCount(0);
        NumPersonas();
        MostrarTabla();
        LimpiarCasillas();
        datos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tablaListaMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListaMaterialMouseClicked
        Seleccionar();
    }//GEN-LAST:event_tablaListaMaterialMouseClicked

    private void btnGuardarModificacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarModificacion1ActionPerformed
        GuardarModificaciones();
        DefaultTableModel model = (DefaultTableModel) this.tablaListaMaterial.getModel();
        model.setRowCount(0);
        model.setRowCount(0);
        MostrarTabla();
        LimpiarCasillas();
        datos();
    }//GEN-LAST:event_btnGuardarModificacion1ActionPerformed

    private void btnModificarId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarId1ActionPerformed
        EntradaMultiple();
    }//GEN-LAST:event_btnModificarId1ActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) this.tablaListaMaterial.getModel();
        model.setRowCount(0);
        model.setRowCount(0);
        Buscar();
        LimpiarCasillas();
        datos();
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        GuardarNuevoId();
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!txtId.getText().equals("") || !txtProducto.getText().equals("")
                || !txtProveedor.getText().equals("") || !txtPresentacion.getText().equals("")
                || !txtAlmacenaje.getText().equals("") || !txtNombreComercial.getText().equals("")
                || !txtDepartamento.getText().equals("")) {
            eliminarFila();
            LimpiarCasillas();
            modificarFileEntrada();
            DefaultTableModel model = (DefaultTableModel) this.tablaListaMaterial.getModel();
            model.setRowCount(0);
            model.setRowCount(0);
            MostrarTabla();
            datos();
        } else {
            JOptionPane.showMessageDialog(null, "No hay datos seleccionados");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NumPersonas;
    private javax.swing.JMenuItem btnActualizar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JMenuItem btnCrearFichero;
    private javax.swing.JMenuItem btnEliminar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnGuardarModificacion1;
    private javax.swing.JMenuItem btnLimpiarDatos;
    private javax.swing.JButton btnModificarId1;
    private javax.swing.JMenuItem btnSalirMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaListaMaterial;
    private javax.swing.JTextField txtAlmacenaje;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombreComercial;
    private javax.swing.JTextField txtPresentacion;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtProveedor;
    // End of variables declaration//GEN-END:variables
}
