package jframe;

import jframe.menuPrincipal.MiRenderer;
import jframe.menuPrincipal.date;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Gustavo_Senorans
 */
public final class StockRopa extends javax.swing.JFrame {

    date date = new date();
    String user = System.getProperty("user.name");
    File fichero2 = new File("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\JFrame\\src\\file\\entrada.csv");
    File fichero = new File("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\JFrame\\src\\file\\stockropa.csv");
    File fichero_temporal = new File("C:\\Users\\" + user + "\\Documents\\NetBeansProjects\\JFrame\\src\\file\\temporal.csv");
    File ficheroStockRopa = new File("C:\\Users\\" + user + "\\Desktop\\Fichero_Stock_Ropa.csv");

    /**
     * Creates new form StockRopa
     */
    public StockRopa() {
        initComponents();
        ficheroApp();
        this.setTitle("Stock Ropa");
        this.setLocationRelativeTo(StockRopa.this);
        setIconImage(new ImageIcon(getClass().getResource("/img/IconoJFrame.png")).getImage());
        this.getContentPane().setBackground(new Color(243, 233, 147));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(true);
        MostrarTabla();
        NumPersonas();
        tablaStockRopa.getTableHeader().setFont(new Font("Courier New", 1, 18));
        tablaStockRopa.getTableHeader().setBackground(Color.blue);
        tablaStockRopa.getTableHeader().setForeground(Color.white);

        MiRenderer m = new MiRenderer();
        for (int i = 0; i < tablaStockRopa.getColumnCount(); i++) {
            tablaStockRopa.getColumnModel().getColumn(i).setCellRenderer(m);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaStockRopa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        NumPersonas = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtTalla59 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtTalla60 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtTalla40 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTalla41 = new javax.swing.JTextField();
        txtTalla42 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTalla43 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTalla44 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTalla45 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTalla46 = new javax.swing.JTextField();
        txtTalla47 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTalla48 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtTalla49 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTalla50 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTalla51 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTalla52 = new javax.swing.JTextField();
        txtTalla53 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTalla54 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtTalla55 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtTalla56 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtPrenda = new javax.swing.JTextField();
        txtTalla57 = new javax.swing.JTextField();
        txtTalla36 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTalla58 = new javax.swing.JTextField();
        txtTalla37 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTalla38 = new javax.swing.JTextField();
        txtTalla39 = new javax.swing.JTextField();
        btnGuardar1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnActualizarMenu = new javax.swing.JMenuItem();
        btnLimpiarDatosMenu = new javax.swing.JMenuItem();
        btnFicheroMenu = new javax.swing.JMenuItem();
        btnSalirMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 233, 147));

        tablaStockRopa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaStockRopa.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        tablaStockRopa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prenda", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "Total", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaStockRopa.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tablaStockRopa.getTableHeader().setReorderingAllowed(false);
        tablaStockRopa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaStockRopaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaStockRopa);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stock Ropa");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Personas dentro de Planta:");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NumPersonas.setEditable(false);
        NumPersonas.setBackground(new java.awt.Color(255, 255, 255));
        NumPersonas.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        NumPersonas.setForeground(new java.awt.Color(204, 0, 0));
        NumPersonas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumPersonas.setBorder(null);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jLabel31.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));

        txtTalla59.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla59.setBorder(null);

        jLabel28.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel28.setText("Talla 60:");

        txtTalla60.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla60.setBorder(null);

        jLabel29.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel29.setText("Total:");

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel6.setText("Talla 39:");

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtTotal.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTotal.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel7.setText("Talla 40:");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtId.setBorder(null);

        txtTalla40.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla40.setBorder(null);

        jLabel30.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel30.setText("Id:");

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel8.setText("Talla 41:");

        txtTalla41.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla41.setBorder(null);

        txtTalla42.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla42.setBorder(null);

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel9.setText("Talla 42:");

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel11.setText("Talla 43:");

        txtTalla43.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla43.setBorder(null);

        jLabel12.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel12.setText("Talla 44:");

        txtTalla44.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla44.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel13.setText("Talla 45:");

        txtTalla45.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla45.setBorder(null);

        jLabel14.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel14.setText("Talla 46:");

        txtTalla46.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla46.setBorder(null);

        txtTalla47.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla47.setBorder(null);

        jLabel15.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel15.setText("Talla 47:");

        txtTalla48.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla48.setBorder(null);

        jLabel16.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel16.setText("Talla 48:");

        txtTalla49.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla49.setBorder(null);

        jLabel17.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel17.setText("Talla 49:");

        txtTalla50.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla50.setBorder(null);

        jLabel18.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel18.setText("Talla 50:");

        txtTalla51.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla51.setBorder(null);

        jLabel19.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel19.setText("Talla 51:");

        jLabel20.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel20.setText("Talla 52:");

        txtTalla52.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla52.setBorder(null);

        txtTalla53.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla53.setBorder(null);

        jLabel21.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel21.setText("Talla 53:");

        txtTalla54.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla54.setBorder(null);

        jLabel22.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel22.setText("Talla 54:");

        txtTalla55.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla55.setBorder(null);

        jLabel23.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel23.setText("Talla 55:");

        jLabel24.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel24.setText("Talla 56:");

        txtTalla56.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla56.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setText("Prenda:");

        jLabel25.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel25.setText("Talla 57:");

        txtPrenda.setEditable(false);
        txtPrenda.setBackground(new java.awt.Color(255, 255, 255));
        txtPrenda.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtPrenda.setBorder(null);

        txtTalla57.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla57.setBorder(null);

        txtTalla36.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla36.setBorder(null);

        jLabel26.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel26.setText("Talla 58:");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setText("Talla 36:");

        txtTalla58.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla58.setBorder(null);

        txtTalla37.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla37.setBorder(null);

        jLabel27.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel27.setText("Talla 59:");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setText("Talla 37:");

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setText("Talla 38:");

        txtTalla38.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla38.setBorder(null);

        txtTalla39.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtTalla39.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTalla42))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTalla41))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTalla40))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTalla39))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTalla38, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTalla49))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTalla48, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTalla47))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTalla46, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTalla56))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTalla55))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTalla54, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTalla60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTalla59))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTalla57)
                                    .addComponent(txtTalla58, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(430, 430, 430)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTalla53, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTalla37))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTalla36, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTalla43))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTalla44))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTalla45, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTalla52))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTalla51))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTalla50, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtTalla36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(txtTalla37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtTalla38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(txtTalla43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(txtTalla44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(txtTalla45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtTalla39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtTalla40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(txtTalla41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(txtTalla50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(txtTalla51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(txtTalla52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtTalla53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel21))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel22)
                                        .addComponent(txtTalla54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel23)
                                        .addComponent(txtTalla55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(txtTalla46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(txtTalla47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(txtTalla48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtTalla57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtTalla58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtTalla59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtTalla60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTalla42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtTalla49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(txtTalla56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(0, 0, 255));
        btnGuardar1.setMnemonic('g');
        btnGuardar1.setText("Guardar");
        btnGuardar1.setToolTipText("<html>Guardar entrada.<br/>Tambien puede usar Alt + g</html>");
        btnGuardar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnGuardar1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(NumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(null);

        jMenu1.setBorder(null);
        jMenu1.setForeground(new java.awt.Color(0, 0, 255));
        jMenu1.setMnemonic('m');
        jMenu1.setText("Menú");
        jMenu1.setToolTipText("<html>Menú principal<br/>stock ropa<br/>Tambien se puede usar Alt + m</html>");
        jMenu1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N

        btnActualizarMenu.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnActualizarMenu.setForeground(new java.awt.Color(0, 0, 255));
        btnActualizarMenu.setText("Actualizar");
        btnActualizarMenu.setBorder(null);
        btnActualizarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnActualizarMenu);

        btnLimpiarDatosMenu.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnLimpiarDatosMenu.setForeground(new java.awt.Color(0, 0, 255));
        btnLimpiarDatosMenu.setText("Limpiar");
        btnLimpiarDatosMenu.setBorder(null);
        btnLimpiarDatosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarDatosMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnLimpiarDatosMenu);

        btnFicheroMenu.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnFicheroMenu.setForeground(new java.awt.Color(0, 0, 255));
        btnFicheroMenu.setText("Crear Fichero");
        btnFicheroMenu.setBorder(null);
        btnFicheroMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicheroMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnFicheroMenu);

        btnSalirMenu.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnSalirMenu.setForeground(new java.awt.Color(255, 0, 0));
        btnSalirMenu.setMnemonic('s');
        btnSalirMenu.setText("Salir");
        btnSalirMenu.setToolTipText("<html>Pulsar para salir<br/>Tambien se puede usar Alt + s<br/>y a continuación entrer</html>");
        btnSalirMenu.setBorder(null);
        btnSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btnSalirMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ficheroApp() {
        if (!fichero.exists()) {
            JOptionPane.showMessageDialog(null, "\nHay un error en los fichero\nhable con el administrador.");
        }
    }

    public void MostrarTabla() {
        String line;
        int i = 0;
        BufferedReader br = null;
        DefaultTableModel model = (DefaultTableModel) tablaStockRopa.getModel();
        TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(model);
        model.setRowCount(0);
        model.setRowCount(0);
        try {
            br = new BufferedReader(new FileReader(fichero));
            while ((line = br.readLine()) != null) {
                String[] tabla = line.split(";");
                tablaStockRopa.setRowSorter(elQueOrdena);
                Vector row = new Vector();
                row.add(tabla[0]);
                row.add(tabla[1]);
                row.add(tabla[2]);
                row.add(tabla[3]);
                row.add(tabla[4]);
                row.add(tabla[5]);
                row.add(tabla[6]);
                row.add(tabla[7]);
                row.add(tabla[8]);
                row.add(tabla[9]);
                row.add(tabla[10]);
                row.add(tabla[11]);
                row.add(tabla[12]);
                row.add(tabla[13]);
                row.add(tabla[14]);
                row.add(tabla[15]);
                row.add(tabla[16]);
                row.add(tabla[17]);
                row.add(tabla[18]);
                row.add(tabla[19]);
                row.add(tabla[20]);
                row.add(tabla[21]);
                row.add(tabla[22]);
                row.add(tabla[23]);
                row.add(tabla[24]);
                row.add(tabla[25]);
                row.add(tabla[26]);
                row.add(tabla[27]);
                model.addRow(row);
            }
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    public void Seleccionar() {
        if (tablaStockRopa.getSelectedRowCount() > 0) {
            txtPrenda.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 0).toString());
            txtTalla36.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 1).toString());
            txtTalla37.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 2).toString());
            txtTalla38.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 3).toString());
            txtTalla39.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 4).toString());
            txtTalla40.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 5).toString());
            txtTalla41.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 6).toString());
            txtTalla42.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 7).toString());
            txtTalla43.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 8).toString());
            txtTalla44.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 9).toString());
            txtTalla45.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 10).toString());
            txtTalla46.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 11).toString());
            txtTalla47.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 12).toString());
            txtTalla48.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 13).toString());
            txtTalla49.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 14).toString());
            txtTalla50.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 15).toString());
            txtTalla51.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 16).toString());
            txtTalla52.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 17).toString());
            txtTalla53.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 18).toString());
            txtTalla54.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 19).toString());
            txtTalla55.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 20).toString());
            txtTalla56.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 21).toString());
            txtTalla57.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 22).toString());
            txtTalla58.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 23).toString());
            txtTalla59.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 24).toString());
            txtTalla60.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 25).toString());
            txtTotal.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 26).toString());
            txtId.setText(tablaStockRopa.getValueAt(tablaStockRopa.getSelectedRow(), 27).toString());
        }
    }

    public void LimpiarCasillas() {
        txtPrenda.setText(null);
        txtTalla36.setText(null);
        txtTalla37.setText(null);
        txtTalla38.setText(null);
        txtTalla39.setText(null);
        txtTalla40.setText(null);
        txtTalla41.setText(null);
        txtTalla42.setText(null);
        txtTalla43.setText(null);
        txtTalla44.setText(null);
        txtTalla45.setText(null);
        txtTalla46.setText(null);
        txtTalla47.setText(null);
        txtTalla48.setText(null);
        txtTalla49.setText(null);
        txtTalla50.setText(null);
        txtTalla51.setText(null);
        txtTalla52.setText(null);
        txtTalla53.setText(null);
        txtTalla54.setText(null);
        txtTalla55.setText(null);
        txtTalla56.setText(null);
        txtTalla57.setText(null);
        txtTalla58.setText(null);
        txtTalla59.setText(null);
        txtTalla60.setText(null);
        txtTotal.setText(null);
        txtId.setText(null);
    }

    public void NumPersonas() {
        String line;
        int i = 0;
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(fichero2));
            while ((line = br.readLine()) != null) {
                String[] numPersonas = line.split(";");
                if (numPersonas[2].equals("DENTRO")) {
                    i++;
                    String numPersonasString = String.valueOf(i);
                    NumPersonas.setText(numPersonasString);
                } else {
                    String SinPersonasString = String.valueOf(i);
                    NumPersonas.setText(SinPersonasString);
                }
            }
            br.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    public void comprobar() {

        try {
            int talla36 = Integer.parseInt(txtTalla36.getText());
            int talla37 = Integer.parseInt(txtTalla37.getText());
            int talla38 = Integer.parseInt(txtTalla38.getText());
            int talla39 = Integer.parseInt(txtTalla39.getText());
            int talla40 = Integer.parseInt(txtTalla40.getText());
            int talla41 = Integer.parseInt(txtTalla41.getText());
            int talla42 = Integer.parseInt(txtTalla42.getText());
            int talla43 = Integer.parseInt(txtTalla43.getText());
            int talla44 = Integer.parseInt(txtTalla44.getText());
            int talla45 = Integer.parseInt(txtTalla45.getText());
            int talla46 = Integer.parseInt(txtTalla46.getText());
            int talla47 = Integer.parseInt(txtTalla47.getText());
            int talla48 = Integer.parseInt(txtTalla48.getText());
            int talla49 = Integer.parseInt(txtTalla49.getText());
            int talla50 = Integer.parseInt(txtTalla50.getText());
            int talla51 = Integer.parseInt(txtTalla51.getText());
            int talla52 = Integer.parseInt(txtTalla52.getText());
            int talla53 = Integer.parseInt(txtTalla53.getText());
            int talla54 = Integer.parseInt(txtTalla54.getText());
            int talla55 = Integer.parseInt(txtTalla55.getText());
            int talla56 = Integer.parseInt(txtTalla56.getText());
            int talla57 = Integer.parseInt(txtTalla57.getText());
            int talla58 = Integer.parseInt(txtTalla58.getText());
            int talla59 = Integer.parseInt(txtTalla59.getText());
            int talla60 = Integer.parseInt(txtTalla60.getText());
            if (talla36 >= 0 && talla37 >= 0 && talla37 >= 0
                    && talla38 >= 0 && talla39 >= 0 && talla40 >= 0
                    && talla41 >= 0 && talla42 >= 0 && talla43 >= 0
                    && talla44 >= 0 && talla45 >= 0 && talla46 >= 0
                    && talla47 >= 0 && talla48 >= 0 && talla49 >= 0
                    && talla50 >= 0 && talla51 >= 0 && talla52 >= 0
                    && talla53 >= 0 && talla54 >= 0 && talla55 >= 0
                    && talla56 >= 0 && talla57 >= 0 && talla58 >= 0
                    && talla59 >= 0 && talla60 >= 0) {
                GuardarModificaciones();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "\nSolo puede escribir números enteros.");
        }
    }

    public void GuardarModificaciones() {
        int i = 0;
        try {
            String line;
            BufferedReader br = null;
            BufferedWriter bw = null;
            br = new BufferedReader(new FileReader(fichero));
            bw = new BufferedWriter(new FileWriter(fichero_temporal));

            while ((line = br.readLine()) != null) {
                String[] busqueda = line.split(";");
                if (busqueda[27].equals(txtId.getText())) {
                    i++;
                    busqueda[0] = txtPrenda.getText();
                    busqueda[26] = txtTotal.getText();
                    busqueda[27] = txtId.getText();
                    int talla36 = Integer.parseInt(txtTalla36.getText());
                    int talla37 = Integer.parseInt(txtTalla37.getText());
                    int talla38 = Integer.parseInt(txtTalla38.getText());
                    int talla39 = Integer.parseInt(txtTalla39.getText());
                    int talla40 = Integer.parseInt(txtTalla40.getText());
                    int talla41 = Integer.parseInt(txtTalla41.getText());
                    int talla42 = Integer.parseInt(txtTalla42.getText());
                    int talla43 = Integer.parseInt(txtTalla43.getText());
                    int talla44 = Integer.parseInt(txtTalla44.getText());
                    int talla45 = Integer.parseInt(txtTalla45.getText());
                    int talla46 = Integer.parseInt(txtTalla46.getText());
                    int talla47 = Integer.parseInt(txtTalla47.getText());
                    int talla48 = Integer.parseInt(txtTalla48.getText());
                    int talla49 = Integer.parseInt(txtTalla49.getText());
                    int talla50 = Integer.parseInt(txtTalla50.getText());
                    int talla51 = Integer.parseInt(txtTalla51.getText());
                    int talla52 = Integer.parseInt(txtTalla52.getText());
                    int talla53 = Integer.parseInt(txtTalla53.getText());
                    int talla54 = Integer.parseInt(txtTalla54.getText());
                    int talla55 = Integer.parseInt(txtTalla55.getText());
                    int talla56 = Integer.parseInt(txtTalla56.getText());
                    int talla57 = Integer.parseInt(txtTalla57.getText());
                    int talla58 = Integer.parseInt(txtTalla58.getText());
                    int talla59 = Integer.parseInt(txtTalla59.getText());
                    int talla60 = Integer.parseInt(txtTalla60.getText());

                    int totalTallas = (talla36 + talla37 + talla38 + talla39
                            + talla40 + talla41 + talla42 + talla43 + talla44 + talla45
                            + talla46 + talla47 + talla48 + talla49 + talla50 + talla51
                            + talla52 + talla53 + talla54 + talla55 + talla56 + talla57
                            + talla58 + talla59 + talla60);

                    String talla36_1 = Integer.toString(talla36);
                    String talla37_2 = Integer.toString(talla37);
                    String talla38_3 = Integer.toString(talla38);
                    String talla39_4 = Integer.toString(talla39);
                    String talla40_5 = Integer.toString(talla40);
                    String talla41_6 = Integer.toString(talla41);
                    String talla42_7 = Integer.toString(talla42);
                    String talla43_8 = Integer.toString(talla43);
                    String talla44_9 = Integer.toString(talla44);
                    String talla45_10 = Integer.toString(talla45);
                    String talla46_11 = Integer.toString(talla46);
                    String talla47_12 = Integer.toString(talla47);
                    String talla48_13 = Integer.toString(talla48);
                    String talla49_14 = Integer.toString(talla49);
                    String talla50_15 = Integer.toString(talla50);
                    String talla51_16 = Integer.toString(talla51);
                    String talla52_17 = Integer.toString(talla52);
                    String talla53_18 = Integer.toString(talla53);
                    String talla54_19 = Integer.toString(talla54);
                    String talla55_20 = Integer.toString(talla55);
                    String talla56_21 = Integer.toString(talla56);
                    String talla57_22 = Integer.toString(talla57);
                    String talla58_23 = Integer.toString(talla58);
                    String talla59_24 = Integer.toString(talla59);
                    String talla60_25 = Integer.toString(talla60);
                    String total = Integer.toString(totalTallas);
                    
                    busqueda[0] = (busqueda[0].replace(busqueda[0], busqueda[0]));
                    busqueda[1] = (busqueda[1].replace(busqueda[1], talla36_1));
                    busqueda[2] = (busqueda[2].replace(busqueda[2], talla37_2));
                    busqueda[3] = (busqueda[3].replace(busqueda[3], talla38_3));
                    busqueda[4] = (busqueda[4].replace(busqueda[4], talla39_4));
                    busqueda[5] = (busqueda[5].replace(busqueda[5], talla40_5));
                    busqueda[6] = (busqueda[6].replace(busqueda[6], talla41_6));
                    busqueda[7] = (busqueda[7].replace(busqueda[7], talla42_7));
                    busqueda[8] = (busqueda[8].replace(busqueda[8], talla43_8));
                    busqueda[9] = (busqueda[9].replace(busqueda[9], talla44_9));
                    busqueda[10] = (busqueda[10].replace(busqueda[10], talla45_10));
                    busqueda[11] = (busqueda[11].replace(busqueda[11], talla46_11));
                    busqueda[12] = (busqueda[12].replace(busqueda[12], talla47_12));
                    busqueda[13] = (busqueda[13].replace(busqueda[13], talla48_13));
                    busqueda[14] = (busqueda[14].replace(busqueda[14], talla49_14));
                    busqueda[15] = (busqueda[15].replace(busqueda[15], talla50_15));
                    busqueda[16] = (busqueda[16].replace(busqueda[16], talla51_16));
                    busqueda[17] = (busqueda[17].replace(busqueda[17], talla52_17));
                    busqueda[18] = (busqueda[18].replace(busqueda[18], talla53_18));
                    busqueda[19] = (busqueda[19].replace(busqueda[19], talla54_19));
                    busqueda[20] = (busqueda[20].replace(busqueda[20], talla55_20));
                    busqueda[21] = (busqueda[21].replace(busqueda[21], talla56_21));
                    busqueda[22] = (busqueda[22].replace(busqueda[22], talla57_22));
                    busqueda[23] = (busqueda[23].replace(busqueda[23], talla58_23));
                    busqueda[24] = (busqueda[24].replace(busqueda[24], talla59_24));
                    busqueda[25] = (busqueda[25].replace(busqueda[25], talla60_25));
                    busqueda[26] = (busqueda[26].replace(busqueda[26], total));
                    busqueda[27] = (busqueda[27].replace(busqueda[27], busqueda[27]));
                }
                bw.write(busqueda[0] + ';' + busqueda[1] + ';' + busqueda[2] + ';'
                        + busqueda[3] + ';' + busqueda[4] + ';' + busqueda[5] + ';'
                        + busqueda[6] + ';' + busqueda[7] + ';' + busqueda[8] + ';'
                        + busqueda[9] + ';' + busqueda[10] + ';' + busqueda[11] + ';'
                        + busqueda[12] + ';' + busqueda[13] + ';' + busqueda[14] + ';'
                        + busqueda[15] + ';' + busqueda[16] + ';' + busqueda[17] + ';'
                        + busqueda[18] + ';' + busqueda[19] + ';' + busqueda[20] + ';'
                        + busqueda[21] + ';' + busqueda[22] + ';' + busqueda[23] + ';'
                        + busqueda[24] + ';' + busqueda[25] + ';' + busqueda[26] + ';'
                        + busqueda[27] + "\n");
            }
            bw.flush();
            br.close();
            bw.close();
            if (i == 0) {
                JOptionPane.showMessageDialog(null, "\nNo se encontraron datos.");
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, date.fecha() + "\nError: " + e);
        }
        fichero.delete();
        fichero_temporal.renameTo(fichero);
    }

    public void toExcel() {
        BufferedWriter bw = null;
        DefaultTableModel model = (DefaultTableModel) tablaStockRopa.getModel();
        try {
            bw = new BufferedWriter(new FileWriter(ficheroStockRopa));
            for (int i = 0; i < model.getColumnCount(); i++) {
                bw.write(model.getColumnName(i) + "\t");
            }
            bw.write("\n");
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    bw.write(model.getValueAt(i, j).toString() + "\t");
                }
                bw.write("\n");
            }
            bw.close();
            JOptionPane.showMessageDialog(null, "\nEl fichero se ha creado correctamente.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "\nError: " + e);
        }
    }

    private void btnSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMenuActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirMenuActionPerformed

    private void btnActualizarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMenuActionPerformed
        DefaultTableModel model = (DefaultTableModel) this.tablaStockRopa.getModel();
        model.setRowCount(0);
        model.setRowCount(0);
        NumPersonas();
        MostrarTabla();
        LimpiarCasillas();
    }//GEN-LAST:event_btnActualizarMenuActionPerformed

    private void btnLimpiarDatosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarDatosMenuActionPerformed
        LimpiarCasillas();
    }//GEN-LAST:event_btnLimpiarDatosMenuActionPerformed

    private void btnFicheroMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicheroMenuActionPerformed
        toExcel();
    }//GEN-LAST:event_btnFicheroMenuActionPerformed

    private void tablaStockRopaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaStockRopaMouseClicked
        Seleccionar();
    }//GEN-LAST:event_tablaStockRopaMouseClicked

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        comprobar();
        DefaultTableModel model = (DefaultTableModel) this.tablaStockRopa.getModel();
        model.setRowCount(0);
        model.setRowCount(0);
        MostrarTabla();
        LimpiarCasillas();
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NumPersonas;
    private javax.swing.JMenuItem btnActualizarMenu;
    private javax.swing.JMenuItem btnFicheroMenu;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JMenuItem btnLimpiarDatosMenu;
    private javax.swing.JMenuItem btnSalirMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaStockRopa;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPrenda;
    private javax.swing.JTextField txtTalla36;
    private javax.swing.JTextField txtTalla37;
    private javax.swing.JTextField txtTalla38;
    private javax.swing.JTextField txtTalla39;
    private javax.swing.JTextField txtTalla40;
    private javax.swing.JTextField txtTalla41;
    private javax.swing.JTextField txtTalla42;
    private javax.swing.JTextField txtTalla43;
    private javax.swing.JTextField txtTalla44;
    private javax.swing.JTextField txtTalla45;
    private javax.swing.JTextField txtTalla46;
    private javax.swing.JTextField txtTalla47;
    private javax.swing.JTextField txtTalla48;
    private javax.swing.JTextField txtTalla49;
    private javax.swing.JTextField txtTalla50;
    private javax.swing.JTextField txtTalla51;
    private javax.swing.JTextField txtTalla52;
    private javax.swing.JTextField txtTalla53;
    private javax.swing.JTextField txtTalla54;
    private javax.swing.JTextField txtTalla55;
    private javax.swing.JTextField txtTalla56;
    private javax.swing.JTextField txtTalla57;
    private javax.swing.JTextField txtTalla58;
    private javax.swing.JTextField txtTalla59;
    private javax.swing.JTextField txtTalla60;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
